name: Create and Build Android Project with Glide

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Android SDK
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip commandlinetools-linux-7583922_latest.zip -d $HOME/android-sdk
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

    - name: Create Android Project
      run: |
        mkdir MyAndroidApp
        cd MyAndroidApp
        gradle init --type android-application

    - name: Add Glide Dependency
      run: |
        cd MyAndroidApp
        echo "dependencies {\n    implementation 'com.github.bumptech.glide:glide:4.15.0'\n    annotationProcessor 'com.github.bumptech.glide:compiler:4.15.0'\n}" >> app/build.gradle

    - name: Build APK
      run: |
        cd MyAndroidApp
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: MyAndroidApp/app/build/outputs/apk/debug/app-debug.apk
