name: Build & Upload All Sample APKs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build all registered sample APKs
        run: |
          set -e
          for n in $(./gradlew projects | grep "^ *[+|]*--- Project ':samples:" | sed "s/.*':samples:\([^']*\)'.*/\1/"); do
            echo "Building $n ..."
            ./gradlew :samples:$n:assembleDebug
            cp "samples/$n/app/build/outputs/apk/debug/app-debug.apk" "${n}-debug.apk"
          done

      - name: Upload all APKs as artifacts (renamed)
        uses: actions/upload-artifact@v4
        with:
          name: glide-sample-apks
          path: ./*-debug.apk
