name: Build & Upload All Sample APKs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build all registered sample APKs
        run: |
          set -e
          for n in flickr giphy svg gallery contacturi imgur; do
            echo "Building $n ..."
            ./gradlew :samples:$n:assembleDebug
            APK_PATH=$(find samples/$n -type f -name "*.apk" | head -n1)
            if [ -f "$APK_PATH" ]; then
              cp "$APK_PATH" "${n}-debug.apk"
              echo "Copied $APK_PATH as ${n}-debug.apk"
            else
              echo "❗ APK not found for $n"
            fi
          done
          ls -lh *-debug.apk || echo "No renamed APKs found"

      - name: Upload all APKs as artifacts (renamed)
        uses: actions/upload-artifact@v4
        with:
          name: glide-sample-apks
          path: ./*-debug.apk
